name = "ImageFiltering"
uuid = "6a3955dd-da59-5b1f-98d4-e7296123deb5"
author = ["Tim Holy <tim.holy@gmail.com>", "Jan Weidner <jw3126@gmail.com>"]
version = "0.6.10"

[deps]
CatIndices = "aafaddc9-749c-510e-ac4f-586e18779b91"
ColorVectorSpace = "c3611d14-8923-5661-9e6a-0046d554d3a4"
ComputationalResources = "ed09eef8-17a6-5b46-8889-db040fac31e3"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
FFTViews = "4f61f5a4-77b1-5117-aa51-3ab5ef4ef0cd"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
ImageCore = "a09fc81d-aa75-5fe9-8630-4744c3626534"
ImageMetadata = "bc367c6b-8a6b-528e-b4bd-a4b897500b49"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MappedArrays = "dbb5928d-eab1-5f90-85c2-b9b0edb7c900"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
TiledIteration = "06e1c1a7-607b-532d-9fad-de7d9aa2abac"

[compat]
CatIndices = "0.2"
ColorVectorSpace = "0.6, 0.7, 0.8"
ComputationalResources = "0.3"
DataStructures = "0.17.7"
FFTViews = "0.3"
FFTW = "0.3, 1"
ImageCore = "0.8.1"
ImageMetadata = "0.9"  # it doesn't actually depend on ImageMetadata, but if present we want arraydata to work
MappedArrays = "0.2"
OffsetArrays = "0.10, 0.11, 1"
Requires = "0.5, 1.0"
StaticArrays = "0.10, 0.11, 0.12"
TiledIteration = "0.2"
julia = "1.1"

[extras]
AxisArrays = "39de3d68-74b9-583c-8d2d-e117c070f3a9"
ImageMetadata = "bc367c6b-8a6b-528e-b4bd-a4b897500b49"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["AxisArrays", "ImageMetadata", "Logging", "Random", "Test"]
